spring.application.name=demo

# 1. Database Connection
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/users}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password= ${DATABASE_PASSWORD:suleimanseif925}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 3. Thymeleaf (kama unatumia)
spring.thymeleaf.cache=false

# Server Port
server.port=${PORT:8080}