spring.application.name=demo

# 1. Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=suleimanseif925
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 3. Thymeleaf (kama unatumia)
spring.thymeleaf.cache=false

# Server Port
server.port=8080